# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      @ ; Programs                                                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

	$terminal = kitty
	$fileManager = nautilus --new-window
	$menu = rofi -show drun
	$browser = zen-browser
	$message = vesktop

	$wallpick = $HOME/.config/rofi/minimal/wallpaper.rasi
	$applauncher = $HOME/.config/rofi/minimal/config.rasi

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      @ ; Autostart                                               ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

	exec-once = awww-daemon
	exec-once = blueman-applet
	exec-once = nm-applet
	exec-once = pkill playerctld
	exec-once = mpd-mpris
	exec-once = waybar 
	exec-once = swaync
	exec-once = hypridle

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
