# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                                                                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      @ ; Window Rule                                             ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

	windowrule {
	    name        = suppress-maximize-events
	    match:class = .*
	
	    suppress_event = maximize
	}

	windowrule {
	    name             = fix-xwayland-drags
	    match:class      = ^$
	    match:title      = ^$
	    match:xwayland   = true
	    match:float      = true
	    match:fullscreen = false
	    match:pin        = false
	
	    no_focus = true
	}
	
	windowrule {
	    name        = move-hyprland-run
	    match:class = hyprland-run
	
	    move  = 20 monitor_h-120
	    float = yes
	}
	
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      @ ; Applications                                            ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛	

# Zen browser

	windowrule {
	    name = zen-transparency
	    match:class = ^(zen)$
	    opacity = 0.95 0.85
	    no_shadow = on
	    no_blur = off
	}
# Spotify
	
	windowrule {
	    name        = spotify-transparency
	    match:class = ^(Spotify)$
	    
	    opacity   = 0.85 0.85 override
	    no_shadow = off
	    no_blur   = off
	}
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
