# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      ZUSQII  -  K I T T Y  C O L O R S  (matugen generated)      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

background            #15130c
foreground            #e8e2d4

cursor                #d7c770
cursor_text_color     #383000

selection_background  #4c472b
selection_foreground  #ece3bd

url_color             #a8d0b5

# Black
color0   #222017
color8   #2c2a21

# Red
color1   #ffb4ab
color9   #93000a

# Green
color2   #a8d0b5
color10  #2a4e3a

# Yellow
color3   #cfc7a2
color11  #4c472b

# Blue
color4   #d7c770
color12  #514700

# Magenta
color5   #c3ecd1
color13  #c3ecd1

# Cyan
color6   #6a5f11
color14  #f4e389

# White
color7   #ccc6b5
color15  #e8e2d4

# Tabs
active_tab_background   #514700
active_tab_foreground   #f4e389
inactive_tab_background #222017
inactive_tab_foreground #ccc6b5
tab_bar_background      #15130c
