# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# MATUGEN GENERATED COLORS FOR HYPRLOCK
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

$primary = rgb(a5c8ff)
$primaryFixed = rgb(d4e3ff)
$background = rgb(111318)
$foreground = rgb(e1e2e9)
$error = rgb(ffb4ab)
$accent = rgb(dabde2)

# Custom Surface variant for input field backgrounds
$surfaceVariant = rgb(43474e)
