# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      ZUSQII  -  K I T T Y  C O L O R S  (matugen generated)      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

background            #111318
foreground            #e1e2e9

cursor                #a5c8ff
cursor_text_color     #00315e

selection_background  #3d4758
selection_foreground  #d8e3f8

url_color             #dabde2

# Black
color0   #1d2024
color8   #282a2f

# Red
color1   #ffb4ab
color9   #93000a

# Green
color2   #dabde2
color10  #553f5e

# Yellow
color3   #bcc7dc
color11  #3d4758

# Blue
color4   #a5c8ff
color12  #214876

# Magenta
color5   #f6d9ff
color13  #f6d9ff

# Cyan
color6   #3c608f
color14  #d4e3ff

# White
color7   #c3c6cf
color15  #e1e2e9

# Tabs
active_tab_background   #214876
active_tab_foreground   #d4e3ff
inactive_tab_background #1d2024
inactive_tab_foreground #c3c6cf
tab_bar_background      #111318
